# This is a basic workflow that is manually triggered

name: Auto PR Main Branch

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: main
          title: "Automated PR: Merge ${{ steps.commit_message.outputs.message }} into main"
          body: "This PR was automatically created and merged by a GitHub Action."
          labels: "automated"
          assignees: "handy-darmawan"
